-- Most errors are produced because Smart Data Access don't regonize max parameter of NVARCHAR declaration. So it converts NVARCHAR(max) to NVARCHAR(0)
-- and that is where the error of zero-length is produced.

INSERT INTO "tuser"."dam.Project_DAM.db::tuser.MODELS" SELECT * FROM "tuser"."MsSQL_MODELS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.UOI_STATUS" SELECT * FROM "tuser"."MsSQL_UOI_STATUS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.UOI_TYPES" SELECT * FROM "tuser"."MsSQL_UOI_TYPES";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.UOI_CONTENT_STATES" SELECT * FROM "tuser"."MsSQL_UOI_CONTENT_STATES";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.UOI_CONTENT_TYPES" SELECT * FROM "tuser"."MsSQL_UOI_CONTENT_TYPES";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.UOI_METADATA_STATES" SELECT * FROM "tuser"."MsSQL_UOI_METADATA_STATES";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.USER_GROUPS" SELECT * FROM "tuser"."MsSQL_USER_GROUPS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.USER_GROUP_USERS" SELECT * FROM "tuser"."MsSQL_USER_GROUP_USERS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.GROUPS" SELECT * FROM "tuser"."MsSQL_GROUPS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.USERS" SELECT USER_ID, LOGIN_ID, NAME, GROUP_ID, CREATE_DT, IS_DISABLED FROM "tuser"."MsSQL_USERS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.PARTICIPANTS" SELECT UOI_ID, FIRST_NAME, LAST_NAME, EMAIL_ENABLED, EMAIL_ADDR, TEAMS_USER_ID FROM "tuser"."MsSQL_PARTICIPANTS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SECURITY_POLICIES" SELECT ID, NAME, DESCR FROM "tuser"."MsSQL_SECURITY_POLICIES";
-- Smth with encoding
-- ERROR INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SECURITY_POLICY_PERMISSIONS" SELECT * FROM "tuser"."MsSQL_SECURITY_POLICY_PERMISSIONS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.MIME_TYPES" SELECT ID, NAME, CONTENT_TYPE, DESCR FROM "tuser"."MsSQL_MIME_TYPES";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.FILE_EXTENSIONS" SELECT MIME_TYPE_ID, ID, FILE_EXTENSION, DESCR, MIME_TYPE FROM "tuser"."MsSQL_FILE_EXTENSIONS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.UOIS" SELECT UOI_ID, LOGICAL_UOI_ID, VERSION, NAME, UOI_STATUS, CONTENT_TYPE, CONTENT_SUBTYPE, UOI_TYPE, IS_EDITABLE, CONTENT_STATE, METADATA_STATE, IS_LATEST_VERSION, META_MODEL_ID, DESCR, THUMB_NAIL_OBJ_ID, THUMB_NAIL_OBJ_LOCATION, SCREEN_RES_OBJ_ID, SCREEN_RES_OBJ_LOCATION, MASTER_OBJ_ID, MASTER_OBJ_NAME, MASTER_OBJ_THEME, MASTER_OBJ_GIST, MASTER_OBJ_SIZE, MASTER_OBJ_UNIT, MASTER_OBJ_NAME_LOC, MASTER_OBJ_MIME_TYPE, IS_MULTI_OBJ_UOI, CONTENT_STATE_USER_ID, CONTENT_STATE_DT, METADATA_STATE_USER_ID, METADATA_STATE_DT, IMPORT_DT, IMPORT_USER_ID, EMBARGO_DT, DOI, BITMAP_WIDTH, BITMAP_HEIGHT, BITMAP_RESOLUTION, BITMAP_ORIENTATION, EXPIRATION_DT, ASSET_NAME, USAGE_SCOPE, USAGE, IS_EXPIRED, EXTERNAL_SOURCE_LINK, MASTER_ASSET_ID FROM "tuser"."MsSQL_UOIS";
ERROR INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_SUB_INDUSTRY" SELECT * FROM "tuser"."MsSQL_SAP_DM_SUB_INDUSTRY";
-- No SAP_DM_SOLUTIONS in ACC MSSQL server;
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_SMART_MASTER" SELECT * FROM "tuser"."MsSQL_SAP_DM_SMART_MASTER";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_SMART_ALIAS" SELECT * FROM "tuser"."MsSQL_SAP_DM_SMART_ALIAS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_SAP_COM_METADATA" SELECT UOI_ID, ASSET, SUB_ASSET, CORE_COMPETENCY, PUBLISH_STATUS, REGISTRATION_LEVEL, SOLUTION_CATEGORY, KEYWORDS, DISCREPANCY_STATUS, EVENTS, PUBLISH_DATE, FIELD_LAST_MODIFIED_DATE, ASSET_LAST_SEND_DATE FROM "tuser"."MsSQL_SAP_DM_SAP_COM_METADATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_PUBLISHING_METADATA" SELECT UOI_ID, EXTERNAL_ID, PUBLISH_DESTINATION, PUBLISH_STATUS FROM "tuser"."MsSQL_SAP_DM_PUBLISHING_METADATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_PARTNER_TYPE" SELECT * FROM "tuser"."MsSQL_SAP_DM_PARTNER_TYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_MARKETING_PLAN" SELECT * FROM "tuser"."MsSQL_SAP_DM_MARKETING_PLAN";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_INDUSTRY_SPEC_LOB" SELECT * FROM "tuser"."MsSQL_SAP_DM_INDUSTRY_SPEC_LOB";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_AUDIENCE" SELECT * FROM "tuser"."MsSQL_SAP_DM_AUDIENCE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_ASSET_DESTINATION" SELECT * FROM "tuser"."MsSQL_SAP_DM_ASSET_DESTINATION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_ADDITIONAL_ASSET_USERS" SELECT * FROM "tuser"."MsSQL_SAP_DM_ADDITIONAL_ASSET_USERS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CRM" SELECT * FROM "tuser"."MsSQL_SAP_CRM";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_TARGET_SEG" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_TARGET_SEG";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_SOLUTION_PRODUCT" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_SOLUTION_PRODUCT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_SOLUTION" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_SOLUTION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_SERVICES" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_SERVICES";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_SAP_COM_PRODUCT" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_SAP_COM_PRODUCT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_REGION" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_REGION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_METADATA" SELECT UOI_ID, LANGUAGE_CD FROM "tuser"."MsSQL_SAP_COMMON_METADATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_LIFECYCLE" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_LIFECYCLE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_INDUSTRY" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_INDUSTRY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_EXTERNAL_APP" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_EXTERNAL_APP";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_COUNTRY1" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_COUNTRY1";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_CMPS_EVENT" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_CMPS_EVENT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_AUDIENCE" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_AUDIENCE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_COMMON_ASSETTYPE" SELECT * FROM "tuser"."MsSQL_SAP_COMMON_ASSETTYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_PROJECT_IDS" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_PROJECT_IDS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_METADATA" SELECT UOI_ID, MATERIAL_NUMBER, CMP_ID_NUMBER, LANGUAGE, ASSET_CATEGORY, ASSET_TYPE, TARGET_SEGMENT, MAIN_CATEGORY, MC_ENTERPRISE_APP, MC_BUSINESS_SOLUTION, MC_MIDSIZE_SOLUTION, MC_INDUSTRY, MC_SERVICE, MC_PARTNER, MC_PLATFORM, VALUE_SCENARIO, REGION, COUNTRY, SAP_BOARD_AREA, PAGE_FORMAT, REQUESTED_BY, MC_OTHER FROM "tuser"."MsSQL_SAP_CMPS_METADATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMP_METADATA" SELECT UOI_ID, CMP_TGP_INFORMATION, CMP_DOCUMENT_FORMAT FROM "tuser"."MsSQL_SAP_CMP_METADATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CAG" SELECT * FROM "tuser"."MsSQL_SAP_CAG";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_ASSET_STATUS" SELECT * FROM "tuser"."MsSQL_SAP_ASSET_STATUS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.VIDEO_URLS" SELECT * FROM "tuser"."MsSQL_VIDEO_URLS";
-- Can not import OBJECT_STACKS;
-- Can not import WORKFLOW_LOGS_Full_Search;
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.WORKFLOW_LOGS_Logins" SELECT * FROM "tuser"."MsSQL_WORKFLOW_LOGS_Logins";
-- Can not import WORKFLOW_LOGS_Model_Search;
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.WORKFLOW_LOGS_preview" SELECT * FROM "tuser"."MsSQL_WORKFLOW_LOGS_preview";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.WORKFLOW_LOGS_Upload_Download" SELECT * FROM "tuser"."MsSQL_WORKFLOW_LOGS_Upload_Download";
-- Can not import WORKFLOW_LOGS;
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_YEAR_LU" SELECT * FROM "tuser"."MsSQL_SAP_YEAR_LU";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_METADATA" SELECT UOI_ID, ASSET_TYPE_CD, CAMPAIGN_NAME, CAMPAIGN_LIFECYCLE_CD, CAMPAIGN_STATUS_CD, CAMPAIGN_TYPE_CD, CONTACT_NAME, DESCRIPTION, PARTNER_NAME, ASSET_NAME, ASSET_CD, PROGRAMNAME_CD, PROGRAMTYPE_CD, CAMPAIGN_ID, YEAR, MAUI, CRM_WBS_ELEMEMENT, LEAD_REGION, PROGRAM_ID, CAG_MANAGER, CAG_CAMPAIGN, CAG_PROGRAM, CAG_MASTER_ASSET, CAG_OBJECTIVES, CAG_MESSAGING, CAG_EXECUTION, CAG_GTM, CONTACT_EMAIL FROM "tuser"."MsSQL_SAP_DM_METADATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_IMAGE_METADATA" SELECT * FROM "tuser"."MsSQL_SAP_IMAGE_METADATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SECURITY_POLICY_UOIS" SELECT * FROM "tuser"."MsSQL_SECURITY_POLICY_UOIS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_DM_APPROVAL_DATA" SELECT * FROM "tuser"."MsSQL_SAP_DM_APPROVAL_DATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.UOIS_FULLTEXT_METADATA" SELECT * FROM "tuser"."MsSQL_UOIS_FULLTEXT_METADATA";
-- Can not import sap_wcms_products;
-- Can not import sap_wcms_partner_types;
-- Can not import sap_wcms_metadata_mapping;
-- Can not import sap_wcms_service_mapping;
-- Can not import sap_wcms_lob_mapping;
-- Can not import sap_wcms_language_mapping;
-- Can not import sap_wcms_sub_industry_mapping;
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_COMMON_YES_NO" SELECT * FROM "tuser"."MsSQL_SAP_LU_COMMON_YES_NO";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_MAP_SAPCOM_PRODUCTS_TO_SOLUTIONS" SELECT * FROM "tuser"."MsSQL_SAP_MAP_SAPCOM_PRODUCTS_TO_SOLUTIONS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_PROGRAM_ID" SELECT ID, VALUE, DESCRIPTION FROM "tuser"."MsSQL_SAP_PROGRAM_ID";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_MKT_LU_USAGE" SELECT * FROM "tuser"."MsSQL_SAP_MKT_LU_USAGE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_MKT_LU_REGION" SELECT * FROM "tuser"."MsSQL_SAP_MKT_LU_REGION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_MKT_LU_PROGRAM" SELECT * FROM "tuser"."MsSQL_SAP_MKT_LU_PROGRAM";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_MKT_LU_COUNTRY" SELECT * FROM "tuser"."MsSQL_SAP_MKT_LU_COUNTRY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_PAGE_FORMAT" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_PAGE_FORMAT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_IMG_LU_ASSET_TYPE" SELECT * FROM "tuser"."MsSQL_SAP_IMG_LU_ASSET_TYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_IMAGE_TYPES" SELECT * FROM "tuser"."MsSQL_SAP_IMAGE_TYPES";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_VALUE_SCENARIO" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_VALUE_SCENARIO";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_TARGET_SEGMENT" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_TARGET_SEGMENT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_SAP_BOARD_AREA" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_SAP_BOARD_AREA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_REGION" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_REGION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMP_DOCUMENT_FORMAT" SELECT * FROM "tuser"."MsSQL_SAP_CMP_DOCUMENT_FORMAT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_MC_SERVICE" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_MC_SERVICE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_MC_PLATFORM" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_MC_PLATFORM";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_MC_PARTNER" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_MC_PARTNER";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_MC_MIDSIZE_SOLUTION" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_MC_MIDSIZE_SOLUTION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_MC_INDUSTRY" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_MC_INDUSTRY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_MC_ENTERPRISE_APP" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_MC_ENTERPRISE_APP";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_MC_BUSINESS_SOLUTION" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_MC_BUSINESS_SOLUTION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_MAIN_CATEGORY" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_MAIN_CATEGORY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_LANGUAGE" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_LANGUAGE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_EVENT" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_EVENT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_COUNTRY" SELECT ID, VALUE, DESCRIPTION, LU_CODE FROM "tuser"."MsSQL_SAP_CMPS_COUNTRY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.sap_cmps_asset_type_mk_asset" SELECT * FROM "tuser"."MsSQL_sap_cmps_asset_type_mk_asset";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_ASSET_TYPE" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_ASSET_TYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_ASSET_CATEGORY" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_ASSET_CATEGORY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMPS_ARCHIVE_SERVER_PATHS" SELECT * FROM "tuser"."MsSQL_SAP_CMPS_ARCHIVE_SERVER_PATHS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMP_USAGE_SCOPE" SELECT * FROM "tuser"."MsSQL_SAP_CMP_USAGE_SCOPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_CMP_TGP_INFORMATION" SELECT * FROM "tuser"."MsSQL_SAP_CMP_TGP_INFORMATION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_TARGET_SEGMENT" SELECT * FROM "tuser"."MsSQL_SAP_LU_TARGET_SEGMENT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SUB_INDUSTRY" SELECT * FROM "tuser"."MsSQL_SAP_LU_SUB_INDUSTRY";
-- ERROR SAP_LU_SOLUTIONS does not exist;
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SOLUTION_PRODUCT" SELECT "ID", "VALUE", "DESCRIPTION", IFNULL(RMS_NODE1, NULL), IFNULL(RMS_NODE2, NULL), IFNULL(RMS_NODE3, NULL), "OLD_DAMVALUE" FROM "tuser"."MsSQL_SAP_LU_SOLUTION_PRODUCT"
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SOLUTION" SELECT * FROM "tuser"."MsSQL_SAP_LU_SOLUTION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SERVICES" SELECT * FROM "tuser"."MsSQL_SAP_LU_SERVICES";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SAP_COM_SUB_ASSET_TYPE" SELECT * FROM "tuser"."MsSQL_SAP_LU_SAP_COM_SUB_ASSET_TYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SAP_COM_SOLUTION_CAT" SELECT * FROM "tuser"."MsSQL_SAP_LU_SAP_COM_SOLUTION_CAT";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SAP_COM_REG_LEVEL" SELECT * FROM "tuser"."MsSQL_SAP_LU_SAP_COM_REG_LEVEL";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SAP_COM_PRODUCTS" SELECT * FROM "tuser"."MsSQL_SAP_LU_SAP_COM_PRODUCTS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SAP_COM_EVENTS" SELECT * FROM "tuser"."MsSQL_SAP_LU_SAP_COM_EVENTS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SAP_COM_CORE_COMPETENCY" SELECT * FROM "tuser"."MsSQL_SAP_LU_SAP_COM_CORE_COMPETENCY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SAP_COM_ASSET_TYPE" SELECT * FROM "tuser"."MsSQL_SAP_LU_SAP_COM_ASSET_TYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_SAP_COM_ASSET_DEST" SELECT * FROM "tuser"."MsSQL_SAP_LU_SAP_COM_ASSET_DEST";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_REGION" SELECT * FROM "tuser"."MsSQL_SAP_LU_REGION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_PUBLISH_STATUS" SELECT * FROM "tuser"."MsSQL_SAP_LU_PUBLISH_STATUS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_PARTNER_TYPE" SELECT * FROM "tuser"."MsSQL_SAP_LU_PARTNER_TYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_MARKETING_PLAN" SELECT * FROM "tuser"."MsSQL_SAP_LU_MARKETING_PLAN";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_LOB" SELECT * FROM "tuser"."MsSQL_SAP_LU_LOB";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_LIFECYCLE" SELECT * FROM "tuser"."MsSQL_SAP_LU_LIFECYCLE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_LANGUAGE" SELECT * FROM "tuser"."MsSQL_SAP_LU_LANGUAGE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_INDUSTRY_SPEC_LOB" SELECT * FROM "tuser"."MsSQL_SAP_LU_INDUSTRY_SPEC_LOB";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_INDUSTRY" SELECT * FROM "tuser"."MsSQL_SAP_LU_INDUSTRY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_INCENTIVE" SELECT * FROM "tuser"."MsSQL_SAP_LU_INCENTIVE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_EXTERNAL_APPLICATION" SELECT * FROM "tuser"."MsSQL_SAP_LU_EXTERNAL_APPLICATION";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_DM_CMPGN_TYPE" SELECT * FROM "tuser"."MsSQL_SAP_LU_DM_CMPGN_TYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_DM_CMPGN_STATUS" SELECT * FROM "tuser"."MsSQL_SAP_LU_DM_CMPGN_STATUS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_DM_CMPGN_LCYCLE" SELECT * FROM "tuser"."MsSQL_SAP_LU_DM_CMPGN_LCYCLE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_DM_AUDIENCE" SELECT * FROM "tuser"."MsSQL_SAP_LU_DM_AUDIENCE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_DM_ASSET_TYPE" SELECT * FROM "tuser"."MsSQL_SAP_LU_DM_ASSET_TYPE";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_CUSTOMER" SELECT * FROM "tuser"."MsSQL_SAP_LU_CUSTOMER";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_COUNTRY" SELECT * FROM "tuser"."MsSQL_SAP_LU_COUNTRY";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.META_DATA_STATUS" SELECT * FROM "tuser"."MsSQL_META_DATA_STATUS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.EVENT_CTXTS" SELECT EVENT_ID, CONTEXT_ID, COMPONENT_ID, IS_ENABLED_INTERNAL, IS_ENABLED_EXTERNAL, DESCR, LOGGING_DEST, PUBLICATION_KEY, FILE_DEST, TAB_DEST FROM "tuser"."MsSQL_EVENT_CTXTS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_COUNRTY1" SELECT * FROM "tuser"."MsSQL_SAP_LU_COUNRTY1";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.sap_map_sub_lob" SELECT * FROM "tuser"."MsSQL_sap_map_sub_lob";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.sap_map_sub_industry" SELECT * FROM "tuser"."MsSQL_sap_map_sub_industry";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.sap_map_sub_asset_type" SELECT * FROM "tuser"."MsSQL_sap_map_sub_asset_type";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.sap_mkt_lu_asset" SELECT * FROM "tuser"."MsSQL_sap_mkt_lu_asset";
-- Can not import sap_wcms_solution_category_mapping;
-- Can not import sap_wcms_industry_mapping;
-- Can not import sap_wcms_events_mapping;
-- Can not import sap_wcms_core_competency_mapping;
-- Can not import sap_wcms_company_segment_mapping;
-- Can not import sap_wcms_asset_type_mapping;
-- Can not import sap_wcms_asset_sub_type_mapping;
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_USER_INFO" SELECT * FROM "tuser"."MsSQL_SAP_USER_INFO";
-- Can not import sap_wcms_registration_level_mapping;
-- Can not import sap_wcms_region_mapping;
-- Can not import sap_wcms_marketing_location_mapping;
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.sap_map_sapcom_asset_to_asset" SELECT * FROM "tuser"."MsSQL_sap_map_sapcom_asset_to_asset";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_MCM_OFFER_DATA" SELECT * FROM "tuser"."MsSQL_SAP_MCM_OFFER_DATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_MKT_LU_ASSET_STATUS" SELECT * FROM "tuser"."MsSQL_SAP_MKT_LU_ASSET_STATUS";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.UOIS_FULLTEXT_METADATA" SELECT * FROM "tuser"."MsSQL_UOIS_FULLTEXT_METADATA";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LOB" SELECT * FROM "tuser"."MsSQL_SAP_LOB";
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.VIEW_ELEMENTS" SELECT VIEW_ID, POSITION, ELEMENT_TYPE, ELEMENT_ID, SESSION_ID FROM "tuser"."MsSQL_VIEW_ELEMENTS";

-- additional
INSERT INTO "tuser"."dam.Project_DAM.db::tuser.SAP_LU_APPROVAL" SELECT * FROM "tuser"."MsSQL_SAP_LU_APPROVAL";